project:
  type: website
  render: 
    - handout.qmd
    - advection_dispersion.qmd

website:
  title: "Mini-Lecture UTQ Teach"
  navbar:
    left:
      - href: advection_dispersion.qmd
        text: Exercise
      - href: handout.qmd
        text: Handout

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



